name = "lovelove"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "90467999-5e52-475d-aa51-c2d5798d6056"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
